# Generated by Django 5.2.1 on 2025-05-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleyclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('posicion', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.DateField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('telefono_tutor', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_playera', models.PositiveIntegerField(blank=True, null=True)),
                ('talla_playera', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('ch', 'Chico'), ('m', 'Mediano'), ('g', 'Grande'), ('Xg', 'Extra Grande'), ('XXg', 'Doble Extra Grande')], max_length=10)),
                ('talla_short', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('ch', 'Chico'), ('m', 'Mediano'), ('g', 'Grande'), ('Xg', 'Extra Grande'), ('XXg', 'Doble Extra Grande')], max_length=10)),
                ('talla_licra', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('ch', 'Chico'), ('m', 'Mediano'), ('g', 'Grande'), ('Xg', 'Extra Grande'), ('XXg', 'Doble Extra Grande')], max_length=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voleyclub.categoria')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voleyclub.entrenador')),
            ],
        ),
    ]
