# Generated by Django 5.2.1 on 2025-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleyclub', '0002_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='usa_licra',
            field=models.BooleanField(default=False, help_text='Marca si usa licra en lugar de short.'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='talla_licra',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('ch', 'Chico'), ('m', 'Mediano'), ('g', 'Grande'), ('Xg', 'Extra Grande'), ('XXg', 'Doble Extra Grande')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='talla_short',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('ch', 'Chico'), ('m', 'Mediano'), ('g', 'Grande'), ('Xg', 'Extra Grande'), ('XXg', 'Doble Extra Grande')], max_length=10, null=True),
        ),
    ]
