# Generated by Django 5.2.1 on 2025-05-15 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleyclub', '0003_jugador_usa_licra_alter_jugador_talla_licra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now=True)),
                ('mes_correspondiente', models.CharField(max_length=20)),
                ('concepto', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='voleyclub.jugador')),
            ],
        ),
    ]
