# Generated by Django 5.2.1 on 2025-05-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleyclub', '0004_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('inscripcion', 'Inscripción'), ('mensualidad', 'Mensualidad'), ('uniforme', 'Uniforme'), ('evento', 'Evento'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='mes_correspondiente',
            field=models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], max_length=20),
        ),
    ]
