# Generated by Django 5.2.1 on 2025-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleyclub', '0005_alter_pago_concepto_alter_pago_mes_correspondiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='entrenadores/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
    ]
