# Generated by Django 5.2.1 on 2025-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleyclub', '0006_entrenador_foto_jugador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='acta_nacimiento',
            field=models.FileField(blank=True, null=True, upload_to='jugadores/acta_nacimiento/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='curp',
            field=models.FileField(blank=True, null=True, upload_to='jugadores/curp/'),
        ),
    ]
